rename variable that clashes with Apple's complex.h macro
On Mac, `math.h` imports `complex.h` which defines a macro called `I`. Because the C module uses variables named `I`, compilation fails on Mac.

```
/Users/rachida.seghiri/miniconda3/envs/trace/lib/python3.10/site-packages/numpy/_core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: "Using deprecated NumPy API, disable it with "          "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
   17 | #warning "Using deprecated NumPy API, disable it with " \
      |  ^
tracET/cmodules/supressionmodule.c:64:12: error: expected member name or ';' after declaration specifiers
   64 |     float* I;
      |     ~~~~~  ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/complex.h:42:11: note: expanded from macro 'I'
   42 | #define I _Complex_I
      |           ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/complex.h:40:21: note: expanded from macro '_Complex_I'
   40 | #define _Complex_I (__extension__ 1.0iF)
```